name    'rubiconred-myst'
version '0.3.0'
author 'rubiconred'
license 'Apache License, Version 2.0'
summary 'Oracle Fusion Middleware - WebLogic, SOA, BPM, IDM, WebCenter, Siebel'
description 'MyST is a declarative based, packaged solution for the design, install, 
configuration and continuous deployment of Oracle Fusion Middleware and Applications.'
project_page 'https://github.com/rubiconred'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 0.1.6'